# Generated by Django 5.0.6 on 2024-08-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movieStreamingApp', '0013_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255, unique=True)),
                ('releaseDate', models.DateField()),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')], max_length=5)),
                ('addedDateTime', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('casts', models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.cast')),
                ('countries', models.ManyToManyField(blank=True, to='movieStreamingApp.country')),
                ('directors', models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.director')),
                ('genres', models.ManyToManyField(blank=True, to='movieStreamingApp.genre')),
                ('productions', models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.production')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series_app.series')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('320p', '320p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5)),
                ('source', models.CharField(max_length=255, unique=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series_app.season')),
            ],
            options={
                'unique_together': {('season', 'resolution')},
            },
        ),
    ]
