# Generated by Django 5.0.6 on 2024-08-18 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesresource',
            old_name='season',
            new_name='episode',
        ),
        migrations.AlterUniqueTogether(
            name='seriesresource',
            unique_together={('episode', 'resolution')},
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.PositiveBigIntegerField()),
                ('season', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series_app.season')),
            ],
        ),
    ]
