# Generated by Django 5.0.6 on 2024-08-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_app', '0002_rename_season_seriesresource_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesresource',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series_app.episode'),
        ),
    ]
