# Generated by Django 5.0.6 on 2024-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_app', '0003_alter_seriesresource_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Hiatus', 'Hiatus'), ('Canceled', 'Canceled')], default='Ongoing', max_length=10),
            preserve_default=False,
        ),
    ]
