# Generated by Django 5.0.6 on 2024-07-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_movie_cast_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
    ]
