# Generated by Django 5.0.6 on 2024-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieresource',
            name='resolution',
            field=models.CharField(choices=[('320p', '320p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=5),
        ),
        migrations.AlterField(
            model_name='movieresource',
            name='source',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='movieresource',
            unique_together={('movie', 'resolution')},
        ),
    ]
