# Generated by Django 5.0.6 on 2024-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0006_rename_country_country_name_rename_genre_genre_name_and_more'),
        ('movie_app', '0004_alter_movieresource_resolution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added',
            new_name='addedDateTime',
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, to='movieStreamingApp.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movieStreamingApp.genre'),
        ),
    ]
