# Generated by Django 5.0.6 on 2024-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0012_director'),
        ('movie_app', '0008_movie_productions_movie_rating_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='productions',
            field=models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.production'),
        ),
    ]
