# Generated by Django 5.0.6 on 2024-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0013_cast'),
        ('movie_app', '0009_movie_directors_alter_movie_productions'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(blank=True, null=True, to='movieStreamingApp.cast'),
        ),
    ]
