# Generated by Django 5.0.6 on 2024-07-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0002_remove_director_movie_director_movie'),
        ('movie_app', '0003_remove_movie_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('movie', models.ManyToManyField(blank=True, to='movie_app.movie')),
            ],
        ),
    ]
