# Generated by Django 5.0.6 on 2024-07-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0004_remove_director_movie_remove_production_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='movie',
            new_name='movies',
        ),
    ]
