# Generated by Django 5.0.6 on 2024-08-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0009_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
