# Generated by Django 5.0.6 on 2024-08-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0013_cast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
