# Generated by Django 5.0.6 on 2024-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0015_cast_bio_cast_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
