# Generated by Django 5.0.6 on 2024-09-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieStreamingApp', '0016_alter_cast_bio_alter_cast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='imdb',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
